-- MySQL Script generated by MySQL Workbench
-- Fri Jul 13 13:13:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SpawtDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpawtDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpawtDB` DEFAULT CHARACTER SET utf8 ;
USE `SpawtDB` ;

-- -----------------------------------------------------
-- Table `SpawtDB`.`Amenity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpawtDB`.`Amenity` (
  `AmenityID` INT(11) NOT NULL AUTO_INCREMENT,
  `AmenityName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AmenityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SpawtDB`.`Listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpawtDB`.`Listing` (
  `ListingID` INT(11) NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `Zip` VARCHAR(45) NULL DEFAULT NULL,
  `Rooms` VARCHAR(45) NULL DEFAULT NULL,
  `Rent` VARCHAR(45) NULL DEFAULT NULL,
  `SquareFt` VARCHAR(45) NULL DEFAULT NULL,
  `DogsOK` TINYINT(1) NULL DEFAULT NULL,
  `CatsOK` TINYINT(1) NULL DEFAULT NULL,
  `SmallDogsOK` TINYINT(1) NULL DEFAULT NULL,
  `MediumDogsOK` TINYINT(1) NULL DEFAULT NULL,
  `LargeDogsOK` TINYINT(1) NULL DEFAULT NULL,
  `Insurance` TINYINT(1) NULL DEFAULT NULL,
  `Amenities` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ListingID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SpawtDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpawtDB`.`Users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `UserName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- table for pictures uploaded for listing
CREATE TABLE IF NOT EXISTS `SpawtDB`.`Picture` (
   `PictureID` INT(11) NOT NULL AUTO_INCREMENT,
   `ListingID` INT (11) NOT NULL,
   `PictureLink`  VARCHAR(100) NOT NULL,
   `Tag`  VARCHAR(100) NOT NULL,
   PRIMARY KEY (`PictureID`))
ENGINE = innoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
